args <- commandArgs(TRUE)
if(length(args)!=1) stop("Usage: Rscript demo.R new-project-directory")
root <- args[1]
if(dir.exists(root)) stop("Demo requires a new directory")
dir.create(root,recursive=TRUE)
root <- normalizePath(root)
dir.create(file.path(root,"01_data/raw"),recursive=TRUE)
squares <- lapply(0:2,function(i) sf::st_polygon(list(matrix(c(i,0,i+0.8,0,i+0.8,.8,i,.8,i,0),ncol=2,byrow=TRUE))))
x <- sf::st_sf(code=c("001","002","003"),name=c("Alpha","Beta","Gamma"),cases=c(12,35,21),geometry=sf::st_sfc(squares,crs=4326))
sf::st_write(x,file.path(root,"01_data/raw/demo.geojson"),quiet=TRUE)
script <- sub("^--file=","",grep("^--file=",commandArgs(FALSE),value=TRUE)[1])
source(file.path(dirname(script),"map.R"))
cfg <- list(project=root,source="01_data/raw/demo.geojson",code="code",name="name",value="cases",title="Synthetic cases",unit="cases",static=TRUE)
result <- run_map(cfg)
stopifnot(result$rows==3,result$total==68,result$missing==0)
cfg$output <- "grouped"; cfg$breaks<-c(0,20,40);cfg$labels<-c("Low","High");run_map(cfg)
cfg$output <- "bad";cfg$breaks<-c(0,10)
stopifnot(inherits(try(run_map(cfg),silent=TRUE),"try-error"))
cat("PASS: continuous, grouped, PNG, invalid-break rejection\n")
